import json

with open("api.json") as f:
    schema = json.load(f)

def rust_type_to_ts(t: str, optional: bool = False) -> str:
    if t == "Vec<u8>":
        base = "Uint8Array"
    elif t == "bool":
        base = "boolean"
    elif t in ("u32", "u64"):
        base = "number"
    else:
        base = t
    if optional:
        return f"{base} | null"
    return base

lines = []

lines.append("// This file is auto-generated by generate_ts.py. Do not edit manually.")
lines.append("")

# Size constants
lines.append("// --- Size Constants ---")
lines.append("")
lines.append("export namespace consts_api {")
for c in schema["sz_consts"]:
    name = c["name"]
    value = c["value"]
    try:
        int(value)
        lines.append(f"    export const {name} = {value};")
    except ValueError:
        # expression — emit as-is, referencing sibling consts
        lines.append(f"    export const {name} = {value};")
lines.append("}")
lines.append("")

# Flat const references
lines.append("// Flat const references for use in type aliases")
for c in schema["sz_consts"]:
    name = c["name"]
    lines.append(f"export const {name} = consts_api.{name};")
lines.append("")

# Byte type aliases
lines.append("// --- Byte Type Aliases ---")
lines.append("")
for alias in schema["byte_aliases"]:
    name = alias["name"]
    lines.append(f"export type {name} = Uint8Array;")
lines.append("")

# Struct interfaces grouped by namespace
lines.append("// --- Models ---")
lines.append("")

for namespace_block in schema["models"]:
    ns = namespace_block["namespace"]
    models = namespace_block["models"]

    lines.append(f"export namespace {ns} {{")

    for model_name, model_def in models.items():
        lines.append(f"    export interface {model_name} {{")
        fields = model_def["fields"]
        for field in fields:
            fname = field["name"]
            ftype = field["type"]
            is_optional = field.get("optional", "false") == "true"
            ts_type = rust_type_to_ts(ftype, is_optional)
            opt_marker = "?" if is_optional else ""
            lines.append(f"        {fname}{opt_marker}: {ts_type};")
        lines.append("    }")
        lines.append("")

    lines.append("}")
    lines.append("")
    
    for model_name in models.keys():
        lines.append(f"export type {model_name} = {ns}.{model_name};")
    lines.append("")

output = "\n".join(lines)

with open(".generated/api.ts", "w") as f:
    f.write(output)

print("Generated api.ts")